version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Skipping tests...
      # - npm test   <-- comment or remove this
      - echo Build completed.
artifacts:
  files:
    - '**/*'
